### ISSUE TITLE
Removes all the styles in use and not in use

### ISSUE THREAD

**Issue by GabRobUK** [sonburn/unused-style-remover#2]
I have used this plug-in for some time and it seemed to have worked just fine. After updating to the latest version of Sketch I have noticed that when using this tool, it actually clears all the styles found in the document, whether they are in use or not. Thankfully I have realised the problem soon enough to undo the action, or I would have lost all the text styles created for the App. Thought I let you know about this. Thank you, GR

**Comment by sonburn** [comment]
@GabRobUK thank you for bringing this to my attention. I have been so focused on making Symbol Organizer work again, but now that it is, I will take a look at this next.

**Comment by sonburn** [comment]
@GabRobUK Please download v0.4 and let me know that the plugin is working for you again.

**Comment by GabRobUK** [comment]
Hey all good! It works its magic again. Thank you for fixing it so quickly! 👍

**Comment by sonburn** [comment]
@GabRobUK Thanks for using my plugin!
